### ISSUE TITLE
Questions about the ListenerManager

### ISSUE THREAD

**Issue by enten** [ctrlplusb/react-universally#167] opened 2016-11-08 11:52 UTC
### About `lastConnectionKey` property

The purpose of `lastConnectionKey` is to generate unique identifier for each new connection.
**But its value is never incremented.**

I suggest to patch the `constructor` with:
`-` ~~`const connectionKey = this.lastConnectionKey + 1;`~~
`+` `const connectionKey = this.lastConnectionKey++;`

### About `dipose()` method

Inside `dispose` method: **why you call `killAllConnections` method twice?**

**Comment by ctrlplusb** [comment] 2016-11-08 11:57
Interesting catch on the `lastConnectionKey`.

In regards to the double dispose, I had some strange cases where some connections were still hanging about.  Calling the `killAllConnections` seemed to have helped.  However, perhaps this is a symptom of the `lastConnectionKey` issue you have just highlighted!

**Comment by enten** [comment] 2016-11-08 12:43
> I had some strange cases where some connections were still hanging about

Do you know how can I reproduce this behavior?
I'm interested to solve that "code trick" (calling `killAllConnections` twice).

I've started a project of an "universal application toolchain" (called [tension](https://github.com/enten/tension)) based on your work. I try to adopt a functional approach to reduce tests writing.

Thanks alot for your awesome work!

**Comment by ctrlplusb** [comment] 2016-11-08 12:53
That is super cool to hear! I am always glad to know that people are finding this starter useful to them.  It's great to see that it has been spawning other projects. :)

To be honest I would have to have another play to figure out how to reproduce the behaviour.

One of the biggest pain points with the development server was rebuilding the server whilst a client connection was still bound to it.  I found splitting the server into a server and universalMiddleware component _greatly_ improved the reliability here.  That was probably one of the most critical decisions that I made and I would recommend that you follow the same strategy if at all possible.

**Comment by ctrlplusb** [comment] 2016-11-08 13:15
Thanks for this report @enten 

I have fixed the connection key issue and have removed the second connection kill call as I tried and tried but couldn't reproduce it.  May have been due to the bug you highlighted. :)

I am closing this for now.  Please keep me posted with your project! :)

**Closed by ctrlplusb** 2016-11-08 13:15 UTC
Labels: bug

**Comment by enten** [comment] 2016-11-08 13:50
> I have fixed the connection key issue and have removed the second connection kill call as I tried and tried but couldn't reproduce

Great!

> That was probably one of the most critical decisions that I made

This is not the only one!

The most amazing feature is the **single hot development process which can handle the three components** (with webpack only! I think that is definitely not the purpose of gulp, grunt, bunch or whatever build system because we need a module bundler to do the job).

Do you have a long experience with webpack? [Your webpack configuration factory](https://github.com/ctrlplusb/react-universally/blob/master/tools/webpack/configFactory.js) are amazing too! It inspired me an [another way](https://github.com/enten/tension/blob/master/lib/webpack/configFactory.js) to do that with [a little more flexibility](https://github.com/enten/tension/blob/master/lib/webpack/configBuilder.js).

> Please keep me posted with your project!

Of course!

**Comment by ctrlplusb** [comment] 2016-11-08 14:06
Hot damn @enten that looks amazing!  You are doing some fantastic work.  I see you have a lot of experience with the functional paradigm!  If you don't mind I may steal some of your ideas.  😄 

Thanks for the kind words!  I am so glad you are finding it useful. :)

**Comment by enten** [comment] 2016-11-09 09:36
> I see you have a lot of experience with the functional paradigm!

Not that much. I think it can make code more readable in some cases (mostly facilitate and decrease testing process).

I finished [a first rewriting of your codebase](https://github.com/enten/tension/tree/a744199bfcffad5e6770a77a65af5cc62042ec84/lib) (with some additions like [definitions](https://github.com/enten/tension/blob/a744199bfcffad5e6770a77a65af5cc62042ec84/lib/constants.js#L7) to [allow user to adjust file structure](https://github.com/enten/tension/blob/a744199bfcffad5e6770a77a65af5cc62042ec84/lib/context.js#L113), [files configuration](https://github.com/enten/tension/blob/a744199bfcffad5e6770a77a65af5cc62042ec84/lib/context.js#L88), [environment configuration mapping](https://github.com/enten/tension/blob/a744199bfcffad5e6770a77a65af5cc62042ec84/lib/context.js#L76), [thinner hash computed](https://github.com/enten/tension/blob/a744199bfcffad5e6770a77a65af5cc62042ec84/lib/context.js#L76) for the vendor dll based on detected imports instead of dependencies listed in package.json, [user webpack config hooks to add custom stuff](https://github.com/enten/tension/blob/a744199bfcffad5e6770a77a65af5cc62042ec84/lib/webpack/configBuilder.js#L427)).

The main purpose is to allow developper to starts an universal project with less painful. Like [Next.js](https://zeit.co/blog/next). But Next.js uses gulp (and gulp isn't a module bundler) and hasn't client/ssrMiddleware/server separation. It's very restrictive. I hope to solve these limits with [tension](https://github.com/enten/tension).
I want to be halfway between [electrode](http://www.electrode.io/docs/what_is_electrode.html) and Next.js with a core based on your amazing work.



>  If you don't mind I may steal some of your ideas.  :smile:

Enjoy!

**Comment by enten** [comment] 2016-11-17 13:50
> If you don't mind I may steal some of your ideas.  :smile:

You no longer have to steal anything.

I wrote [wcf](https://github.com/enten/wcf) as a webpack configuration factory inspired from your work on react-universally.

Below a rewrite of your [webpack/configFactory.js](https://github.com/ctrlplusb/react-universally/blob/master/tools/webpack/configFactory.js) with `wcf` (except for `plugins` and `module` options).

```javascript
var wcf = require('wcf')
var path = require('path')

// mocks >
var appRootPath = '.'
var target = 'client'

var envVars = {
  CLIENT_DEVSERVER_PORT: 7331,
  BUNDLE_OUTPUT_PATH: './build',
  CLIENT_BUNDLE_HTTP_PATH: '/client/'
}
// < mocks


// Add target "server" because wcf known standards webpack targets only
// github.com/enten/wcf/blob/4a7eff8bcbb5787ea33f66118e80b73cef1fcd37/index.js#L8
wcf.$target('server', {target: 'node', server: true})

var f = wcf

f._node({
  __dirname: true,
  __filename: true
})

f.devtool('source-map')
f.web.prod.devtool('hidden-source-map')

f.server.externals(/\.\.[/\\]universalMiddleware/)
f.server.dev.externals(/development[/\\]universalDevMiddleware/)

// Note: every helpers have a ${helperName}With method
//
// The purpose here is to load the dependency only if it's needed
// (on f.$build({target: 'node'}) or f.$build({target: 'server'})
f.node.externalsWith(() => require('webpack-node-externals')({
  whitelist: [
    /\.(eot|woff|woff2|ttf|otf)$/,
    /\.(svg|png|jpg|jpeg|gif|ico)$/,
    /\.(mp4|mp3|ogg|swf|webp)$/,
    /\.(css|scss|sass|sss|less)$/
  ]
}))


f.web.dev.entry.index('react-hot-loader/patch')
f.web.dev.entry.index(`webpack-hot-middleware/client?reload=true&path=http://localhost:${envVars.CLIENT_DEVSERVER_PORT}/__webpack_hmr`)
f.web.entry.index('regenerator-runtime/runtime')
f.entry.index(path.resolve(appRootPath, `./src/${target}/index.js`))

f.output.path(path.resolve(appRootPath, envVars.BUNDLE_OUTPUT_PATH, `./${target}`))

f.web.output.filename(
  '[name]-[chunkhash].js',
  // else
  '[name].js'
)

f.output.chunkFilename('[name]-[chunkhash].js')


f.dev.output.publicPath(
  `http://localhost:${envVars.CLIENT_DEVSERVER_PORT}${envVars.CLIENT_BUNDLE_HTTP_PATH}`,
  // else
  envVars.CLIENT_BUNDLE_HTTP_PATH
)

f.node.output.libraryTarget('commonjs2', 'var')

f.resolve.extensions([
  '.js',
  '.jsx',
  '.json'
])

f.plugins('plugin 1')
f.server.plugins('plugin 2')

f.module.rules('module rule 1')
f.web.module.rules('module rule 2')



var clientDevConfig = f.$build({prod: false, target: 'web'})
// or: clientDevConfig = f.web.dev.$build()
var serverDevConfig = f.server.dev.$build()
var universalDevConfig = f.node.dev.$build()

var clientProdConfig = f.web.prod.$build()
var serverProdConfig = f.server.prod.$build()
var universalProdConfig = f.node.prod.$build()


console.dir(clientDevConfig, {depth: null, colors: true})
// { target: 'web',
//   node: { __dirname: true, __filename: true },
//   devtool: 'source-map',
//   entry:
//    { index:
//       [ 'react-hot-loader/patch',
//         'webpack-hot-middleware/client?reload=true&path=http://localhost:7331/__webpack_hmr',
//         'regenerator-runtime/runtime',
//         '/home/steven/code/tension/src/client/index.js' ] },
//   output:
//    { path: '/home/steven/code/tension/build/client',
//      filename: '[name]-[chunkhash].js',
//      chunkFilename: '[name]-[chunkhash].js',
//      publicPath: 'http://localhost:7331/client/',
//      libraryTarget: 'var' },
//   resolve: { extensions: [ '.js', '.jsx', '.json' ] },
//   plugins: [ 'plugin 1' ],
//   module: { rules: [ 'module rule 1', 'module rule 2' ] } }
```
