### ISSUE TITLE
net::ERR_ADDRESS_INVALID

### ISSUE THREAD

**Issue by elazcano-rgare** [ctrlplusb/react-universally#556] opened 2018-02-04 23:25 UTC
show in readme, if you are a windows user, better to use address 127.0.0.1  **instead** 0.0.0.0 in the file:
values.js in config directory....

// The host on which the server should run.
  host: EnvVars.string('HOST', '127.0.0.1')

**Comment by birkir** [comment] 2018-03-14 18:25
Dupe of #379

**Closed as completed by birkir** 2018-03-14 18:25 UTC
Labels: duplicate
