### ISSUE TITLE
Index chunk hash doesn't change when child chunk does

### ISSUE THREAD

**Issue by bradbarrow** [ctrlplusb/react-universally#394] opened 2017-03-10 00:58 UTC
#### Context

I'm using v12
Node 7.4.0

I removed the `code-split-component` since I didn't need it at a route level
I introduced my own code split for a small feature as follows:

```
require.ensure(['../lib/FlagSvg'], (require) => {
  const FlagSvg = require('../lib/FlagSvg').default;
  console.log(FlagSvg(code));
});
```

This works fine, a chunk `0-xxxxxxxxxxxxxxxxx` is created and loaded by my `index-xxxxxx` chunk.

#### What's the issue?

If I change the code in `Lib/FlagSvg` and nothing else...the sha for chunk `0` is updated to `0-yyyyyyyyyyy` for example.

As expected, the `index` chunk now has a reference to `0-yyyyyyyyyyy` in it. BUT the `index` chunk's OWN sha is still `index-xxxxxxxxxxx`.

Therefore, in production...I get back the cached `index-xxxxxxxxxx` which still tries to load `0-xxxxxxxxxxx` instead of `0-yyyyyyyyyyy` and everything blows up - specifically..the module indices are wrong and I get the `call(...) of undefined error` as per https://github.com/webpack/webpack/issues/959

I'm not sure if I have done anything particularly wrong - I may try reproduce on a vanilla install. 

Are you aware of this scenario?

### Further explanation

Disabling the  `webpack-md5-hash` plugin results in all chunk sha's changing as expected: 

![image](https://cloud.githubusercontent.com/assets/1264276/23777942/d3e2b20e-058b-11e7-9dc8-48b73eb12967.png)

Thanks so much for all your work 👍

**Comment by ctrlplusb** [comment] 2017-03-13 14:14
Oh wow, this definitely is not expected behaviour.  Thanks for raising this I will make sure to do some investigation.

**Comment by ctrlplusb** [comment] 2017-03-13 14:17
Looks like a known issue. 😢

https://github.com/erm0l0v/webpack-md5-hash/issues/7

**Comment by ctrlplusb** [comment] 2017-03-13 14:19
@bradbarrow would you mind adding the following to your plugins list and then retest this for us?

```
new webpack.HashedModuleIdsPlugin()
```

**Comment by smirea** [comment] 2017-03-13 15:11
I've had this issue before due to the internal webpack hashing algorithm acting weird. I don't recall the reference solution thread, but the way I solved it was by using a custom hashing function:

```js
const WebpackMd5Hash = require('webpack-md5-hash');
plugins: [
    ...
    new WebpackMd5Hash(),
],
```

this was for webpack1 also, but the behavior looks very similar

**Comment by bradbarrow** [comment] 2017-03-15 04:23
Hey @ctrlplusb yep I can give that a go for you this evening. 

@smirea that's what `react-universally` is currently doing - you'd imagine it to be a good solution since the hash changes when the file contents change...except....when it doesn't :'(

I'll report back @ctrlplusb

**Comment by ctrlplusb** [comment] 2017-04-03 21:25
Hey @bradbarrow 

Did you manage to get a chance to review this?  No pressure. 😀

**Comment by ctrlplusb** [comment] 2017-04-05 14:13
Hey @bradbarrow 

I just tried to recreate this issue, but couldn't do so.

I am using the lastest on `next` and did the following workflow:

  - yarn build
  - yarn start
  - view website
  - edit HomeRoute
  - yarn build
  - yarn start
  - hit website again without hard refresh

The updated code (despite it being a child/async chunk) was loaded.

Hmmm....

**Comment by ctrlplusb** [comment] 2017-04-06 22:07
Closing this for now, please reopen if the problem persists.  Also please include steps to reproduce. 😊

**Comment by ctrlplusb** [comment] 2017-04-26 13:10
Reopening this as I am not convinced it is resolved.

**Comment by bradbarrow** [comment] 2017-04-27 11:54
Hey mate sorry no I never did. We're still using v12 of react-universally in prod (we just turned off code splitting so to speak) 

We're going to migrate to the latest soonish, will have another crack at it then

**Comment by tomkelsey** [comment] 2017-05-04 12:03
Hey - just a quick note to say I believe I'm experiencing this problem too. I haven't dug into it yet but as per @bradbarrow I also removed the code-split-component and have implemented my own code splitting via require.ensure

**Comment by ctrlplusb** [comment] 2018-03-23 14:46
Closing this due to inactivity please let me know if issue persists. Lots of webpack related changes in next may sort this potential issue.

**Closed by ctrlplusb** 2018-03-23 14:46 UTC

**Comment by scripter-co** [comment] 2018-08-21 20:00
Just so you know this still is an issue. I removed code splitting until I can look into this.Just so you know this still is an issue. I removed code splitting until I can look into this.
