### ISSUE TITLE
Debugging server side code

### ISSUE THREAD

**Issue by ritz078** [ctrlplusb/react-universally#347] opened 2017-01-24 08:59 UTC
Any way to support `--inspect` just like node does. Or is there any existing way that I missed to debug server side code. I guess node-inspector supports babel-node.

**Comment by lucianlature** [comment] 2017-01-24 09:26
@ritz078: do you use VSC or WebStorm for development?

**Comment by ritz078** [comment] 2017-01-24 09:31
WebStorm

**Comment by ctrlplusb** [comment] 2017-01-24 09:46
> @ritz078: do you use VSC or WebStorm for development?

Or atom? 😜

**Comment by lucianlature** [comment] 2017-01-24 10:10
@ritz078 

Steps for debugging server side code in Webstorm:

1. `Run` -> `Edit Configurations`
2. `Add new configuration` -> `Node.js`
3. You can name it `ReactUniversally` or whatever you like.
4. For `Node Interpreter` my version is `v7.4.0`, but you'll pick your installed version.
5. For `Node parameters`: `-r babel-register`
6. As `Working directory`: the root directory of your project.
7. For `JavaScript file`: `build/server/index.js`.

The issue is that you'll have to set breakpoints inside `build/server/index.js`, but the `Frames` tab inside `Debugger` will point you to the correct loaded files from `src`, and the variables available inside the block.

Last step: Launch `Debugger` by selecting `Run` -> `Debug ReactUniversally`. Once server started, set a breakpoint and refresh the page.

Enjoy the debugging session! 🎉

**Comment by ritz078** [comment] 2017-01-24 10:13
👍 This is nice. But this is very much specific for a particular IDE. Won't it be nice to add node inspector for greater good. I guess its a important pain that can be addressed and will make this boilerplate even better.

**Comment by lucianlature** [comment] 2017-01-24 10:41
In order to launch the debugger, this command is being executed by WebStorm:

`~/.nvm/versions/node/v7.4.0/bin/node --inspect=58487 --debug-brk -r babel-register ~/WebstormProjects/react-universally/build/server/index.js`

It shouldn't matter which IDE you're using, the debugger will be launched by this line.

**Comment by Graf009** [comment] 2017-01-24 11:01
@lucianlature Thank you. How to configure VSCode?

**Comment by lucianlature** [comment] 2017-01-24 13:47
@Graf009 To debug in VSCode:

1. `View` -> `Debug`
2. `View` -> `Command Palette`
3. Search `launch.json`
4. Add to the `configurations`:
```
 {
     "type": "node",
     "request": "launch",
     "name": "Launch ReactUniversally",
     "program": "${workspaceRoot}/build/server/index.js",
     "cwd": "${workspaceRoot}"
}
```
5. `Start debugging`.
6. Set debugging points in `build/server/index.js`
7. You should have now a snapshot of variables, call stack, watch variables and breakpoints in `debug` view.

**Comment by RishabhJain96** [comment] 2017-01-28 05:41
Wouldn't a more generic approach be to allow arguments to be attached to `spawn` in hotNodeServer? At the very least, perhaps allow arguments to be added from a config entry.

For example (in hotNodeServer.js):
`const newServer = spawn('node', [compiledEntryFile])`

can be changed to be something such as (ideally, `--inspect` should be read from config)
`const newServer = spawn('node', ['--inspect', '--debug-brk', compiledEntryFile)`

**Comment by ctrlplusb** [comment] 2017-04-05 15:35
Closing this to keep issues list more focused.

**Closed by ctrlplusb** 2017-04-05 15:35 UTC
Labels: question
