### ISSUE TITLE
[Discussion] Build a proper dist

### ISSUE THREAD

**Issue by carsonperrotti** [ctrlplusb/react-universally#267] opened 2016-12-21 14:57 UTC
I would like to raise the discussion around having the build script prepare a proper or fully encapsulated `dist`. Deploying to services like Heroku are a bit of a pain or not straight forward using this starter and require some trickery with devDependencies. 

Questions are:
- Is this a possible task?
- Is it worth doing?
- What needs to change in order for this to happen?

**Comment by ctrlplusb** [comment] 2016-12-21 21:10
I am keen for some new insight here. :)  It would be great to get a dist workflow going, previous discussions (#93) have raised difficulties around this.

**Comment by carsonperrotti** [comment] 2016-12-22 14:37
If I remember correctly, @strues aren't you creating a dist for boldr?

**Comment by strues** [comment] 2016-12-22 18:26
Yeah, @carsonperrotti I am. However, I've not got it completely dialed in yet. I'll finish what've been putting together and post it up here. You're mainly focused on being able to deploy without installing the dev dependencies, right?

**Comment by LorbusChris** [comment] 2016-12-22 20:48
I haven't tested it, but there might be a simple workaround for this.

After building, before deploying, run:

`rm -rf node_modules && npm install --production`

Deletes the node_modules folder and then re-installs just the production deps (omitting devDependencies).

Unfortunately, the --production flag is currently broken in yarn  (https://github.com/yarnpkg/yarn/issues/761)

**Comment by carsonperrotti** [comment] 2016-12-23 15:20
@strues Correct. I am still trying to perfect my deployment process, so any feedback would be ideal too. I use CI and deploy to Heroku, so I don't check in the build folder, so @LorbusChris' suggestion doesn't quite work for me as it pulls from github. If there's a better way to handle this I'm open to it.

**Comment by bkniffler** [comment] 2016-12-28 15:16
I'm not sure what the problem is. Why not either

- Build on workstation: Check-in the build folder and let heroku use production dependencies (without devDependencies) 
- Build on CI: Let a CI create the build folder and commit that to Heroku. For that purpose, I have a '.build' folder for development (ignored) and a 'build' folder (not ignored). I think it makes a lot of sense to separate these.
- Build on Heroku: Let Heroku do build by postinstall hook and installing devDependencies

**Comment by codepunkt** [comment] 2017-01-04 22:46
So you wouldn't advise to just check out the sources on production server, doing a `yarn && yarn run build && yarn run start`there afterwards? Is the goal not having sources or dev dependencies on the production server?

**Comment by carsonperrotti** [comment] 2017-01-05 14:12
Most environments (server and CI) discourage devDependencies for a reason, so why are we working around that?

My main goals for this are to not have "workarounds" to get devDependencies to install as well as keeping the source files on the server as clean as possible. The first of those two issues still exists even when using CI to deploy.

**Comment by codepunkt** [comment] 2017-01-05 21:12
I'm not sure i understand. What is the use case? I'm not even sure i understand what you mean by "fully encapsulated dist"?

**Comment by ctrlplusb** [comment] 2017-04-04 15:17
I am closing this for now, please feel free to reopen if and when we have an solid directions here.

**Closed by ctrlplusb** 2017-04-04 15:17 UTC
Labels: discussion
